<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeastar-PC" name="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound" tests="18" failures="2" timestamp="9 Nov 2017 11:04:01 GMT" time="759.377" errors="0">
  <testcase name="A_callfrom5_fxo" time="31.280" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="A_callfrom6_bri" time="31.288" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="F_timecondition4" time="55.965" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="A_callfrom1_sip" time="38.305" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound">
    <failure type="java.lang.AssertionError" message=" 录音失败">
      <![CDATA[java.lang.AssertionError:  录音失败
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound.A_callfrom1_sip(Inbound.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- A_callfrom1_sip -->
  <testcase name="B2_callerid" time="71.095" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="A_callfrom8_gsm" time="0.000" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="A_callfrom3_sps" time="31.513" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="G_delete1" time="81.089" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="B1_callerid" time="46.345" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="F_timecondition1" time="10.373" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="F_timecondition5" time="62.512" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="C2_did1_sps" time="63.520" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="F_timecondition2" time="76.079" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="A_callfrom7_e1" time="0.000" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="C1_did1_sps" time="26.576" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="A_callfrom4_spx" time="28.020" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound">
    <failure type="java.lang.AssertionError" message="CDR源中继检测 【预期：SPX1 实际：SPS1】">
      <![CDATA[java.lang.AssertionError: CDR源中继检测 【预期：SPX1 实际：SPS1】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:199)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:261)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:250)
	at com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound.A_callfrom4_spx(Inbound.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- A_callfrom4_spx -->
  <testcase name="A_callfrom2_iax" time="31.299" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
  <testcase name="F_timecondition3" time="74.118" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound"/>
</testsuite> <!-- com.yeastar.swebtest.testcase.RegressionCase.pbxcore.Inbound -->
