<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="syscore"
           tests="7"
           failures="1"
           errors="0"
           skipped="0"
           time="107.661">
  <properties />
            <testcase name="C_Answer" time="24.415" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter">
                <failure type="java.lang.AssertionError"
                  message="分机1100接听 【预期：true 实际：false】"
              >
<![CDATA[java.lang.AssertionError: 分机1100接听 【预期：true 实际：false】
  com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
  com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:333)
  com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter.C_Answer(EventCenter.java:77)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  org.testng.TestNG.run(TestNG.java:1048)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="E_DeleteNotification" time="8.360" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter" />
                <testcase name="G_CheckLog" time="13.078" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter" />
                <testcase name="F_CheckLog" time="24.157" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter" />
                <testcase name="A_AddContact" time="18.383" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter" />
                <testcase name="B_EventSettings" time="6.331" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter" />
                <testcase name="D_CheckEventLog" time="12.937" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter" />
      
</testsuite>
