<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeastar-PC" name="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber" tests="50" failures="4" timestamp="22 Apr 2018 04:56:57 GMT" time="1906.942" errors="0">
  <testcase name="B1_addEmergencyNum" time="31.759" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter8" time="73.205" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C1_edittrunk_Unavail" time="34.255" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G3_deleteOne_yes" time="24.747" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C2_checkUnavailTrunk" time="32.666" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D3_check_iax" time="52.502" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C4_checkTrunk2" time="102.940" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="java.lang.AssertionError" message="CDR呼叫方检测 【预期：1100 [1100] 实际：1100dial1234567890123456789012345678901 [Emergency]】">
      <![CDATA[java.lang.AssertionError: CDR呼叫方检测 【预期：1100 [1100] 实际：1100dial1234567890123456789012345678901 [Emergency]】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:199)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:262)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.C4_checkTrunk2(EmergencyNumber.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- C4_checkTrunk2 -->
  <testcase name="B2_makeCall" time="52.056" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C7_deleteNotification" time="26.245" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="B4_makeCall1" time="11.102" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter2" time="73.807" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C8_checkNotification" time="53.086" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter3" time="11.514" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E2_checkVoipAndPhy" time="52.429" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="A1_registerExtensions" time="51.435" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F3_recoveryEvent" time="19.942" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter1" time="10.031" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E4_checkPhyAndVoip" time="82.522" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="java.lang.AssertionError" message="CDR目的中继检测 【预期：SPS1 实际：FXO7】">
      <![CDATA[java.lang.AssertionError: CDR目的中继检测 【预期：SPS1 实际：FXO7】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:199)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:269)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.E4_checkPhyAndVoip(EmergencyNumber.java:659)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- E4_checkPhyAndVoip -->
  <testcase name="F2_EventCenter4" time="8.036" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F1_Contacts3" time="22.135" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G6_deleteAll_no" time="9.722" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C6_checkTrunk" time="71.947" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D4_check_spx" time="52.126" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D5_check_bri" time="52.416" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="B3_editEmergencyNumb" time="34.440" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E3_PhyAndVoip" time="35.600" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G1_addNumber" time="3.662" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter6" time="15.352" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F1_Contacts1" time="27.225" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C3_addTrunk" time="45.151" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E5_PhyAndPhy" time="35.559" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G5_deletePart_yes" time="13.360" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G7_delteAll_yes" time="13.294" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F1_Contacts2" time="71.536" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E1_voipAndPhysical" time="44.355" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter7" time="10.071" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C4_checkTrunk1" time="54.103" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="H_recovery" time="43.647" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G2_deleteOne_no" time="15.197" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="A2_addUnavailTrunk" time="21.649" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E6_checkPhyAndPhy" time="74.255" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="java.lang.AssertionError" message="CDR目的中继检测 【预期：BRI1 实际：FXO7】">
      <![CDATA[java.lang.AssertionError: CDR目的中继检测 【预期：BRI1 实际：FXO7】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:199)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:269)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.E6_checkPhyAndPhy(EmergencyNumber.java:721)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- E6_checkPhyAndPhy -->
  <testcase name="B4_makeCall2" time="52.326" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D7_check_gsm" time="0.012" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter5" time="54.212" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="com.codeborne.selenide.ex.ElementShould" message="Element should be visible {By.xpath: .//span[starts-with(@class,&quot;x-btn-inner x-btn-inner-default-small&quot;) and text()=&quot;Search&quot;]}
Element: &#039;&lt;span class=&quot;x-btn-inner x-btn-inner-default-small&quot; data-ref=&quot;btnInnerEl&quot; id=&quot;st-el-search-btnInnerEl&quot; unselectable=&quot;on&quot; displayed:false&gt;&lt;/span&gt;&#039;">
      <![CDATA[Element should be visible {By.xpath: .//span[starts-with(@class,"x-btn-inner x-btn-inner-default-small") and text()="Search"]}
Element: '<span class="x-btn-inner x-btn-inner-default-small" data-ref="btnInnerEl" id="st-el-search-btnInnerEl" unselectable="on" displayed:false></span>'
Screenshot: file:/F:/MyProject/SwebTest/build/reports/tests/1524350487760.5.png
Timeout: 15 s.
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:66)
	at com.codeborne.selenide.impl.WebElementSource.findAndAssertElementIsVisible(WebElementSource.java:72)
	at com.codeborne.selenide.commands.Click.execute(Click.java:14)
	at com.codeborne.selenide.commands.Click.execute(Click.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:140)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:86)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:62)
	at com.sun.proxy.$Proxy6.click(Unknown Source)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:260)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.F2_EventCenter5(EmergencyNumber.java:900)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- F2_EventCenter5 -->
  <testcase name="D5_check_pstn" time="56.326" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D6_check_e1" time="0.021" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter9" time="24.245" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D1_addEmergency_line" time="99.666" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G4_deletePart_no" time="18.358" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C5_deleteTrunk_addNotification" time="30.695" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
</testsuite> <!-- com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber -->
