<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeastar-PC" name="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue" tests="105" failures="15" timestamp="18 Oct 2018 08:09:17 GMT" time="3456.388" errors="0">
  <testcase name="Fa_dynamic_login6714" time="19.298" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G5_Satisfaction" time="130.070" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="坐席挂断时播放满意度调查提示音satisfaction 【预期：true 实际：false】">
      <![CDATA[java.lang.AssertionError: 坐席挂断时播放满意度调查提示音satisfaction 【预期：true 实际：false】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:337)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.G5_Satisfaction(Queue.java:904)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- G5_Satisfaction -->
  <testcase name="C3_iax_6701" time="0.041" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="C1_sps_6701" time="46.992" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="F5_dynamic_login6710" time="15.960" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G6_CallerPosition" time="0.041" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E4_key3_ivr" time="45.894" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D3_fail_voicemail1" time="63.075" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G2_JoinAnnouncement" time="14.225" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="C4_spx_6701" time="0.013" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="J1_random" time="0.011" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G9_warp_time0" time="5.864" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1100会同时Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1100会同时Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.G9_warp_time0(Queue.java:968)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- G9_warp_time0 -->
  <testcase name="A4_AddQueues" time="44.276" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E3_key2_voicemail1" time="59.536" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="41.704" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D3_fail_voicemail2_check" time="47.586" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B1_AddInbound" time="60.471" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="C8_gsm_6701" time="0.016" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="N8_leave_join_empty" time="23.100" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D6_fail_queue" time="68.949" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="41.125" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="P2_recovery" time="88.688" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.393" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="F6_dynamic_login6711" time="15.930" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="L1_linear" time="28.798" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1000第1个Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1000第1个Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.L1_linear(Queue.java:1139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- L1_linear -->
  <testcase name="F2_dynamic_call6701" time="59.890" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="F9_dynamic_login6714" time="9.103" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G3_MusicOnHold2" time="5.460" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E3_key2_voicemail3_login" time="30.898" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.356" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.705" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E6_key5_queue" time="52.338" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="31.602" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="P1_recovery" time="74.216" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.608" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.441" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.582" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D2_fail_extension" time="50.438" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="L2_linear" time="97.709" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1101第4个Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1101第4个Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.L2_linear(Queue.java:1168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- L2_linear -->
  <testcase name="B2_AddInbound" time="20.993" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="34.643" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A3_Init" time="43.638" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.865" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G7_PeriodicAnnouncements" time="0.033" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B3_Apply" time="8.112" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="K2_rrmemory" time="29.124" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="CDR被叫方检测 【预期：1105 [6713(1105)] 实际：6713】">
      <![CDATA[java.lang.AssertionError: CDR被叫方检测 【预期：1105 [6713(1105)] 实际：6713】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:203)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:289)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:278)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.K2_rrmemory(Queue.java:1131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- K2_rrmemory -->
  <testcase name="C6_bri_6701" time="0.020" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E3_key2_voicemail2_check" time="52.430" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D5_fail_ringgroup" time="45.366" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="37.138" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="43.972" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="C2_sip_6701" time="49.009" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G8_AgentTimeout_Retry" time="11.659" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1101会同时Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1101会同时Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.G8_AgentTimeout_Retry(Queue.java:928)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- G8_AgentTimeout_Retry -->
  <testcase name="N0_backup" time="42.406" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="I3_fewestcalls" time="21.569" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1000会Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1000会Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.I3_fewestcalls(Queue.java:1090)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- I3_fewestcalls -->
  <testcase name="F8_dynamic_login6713" time="21.075" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G3_MusicOnHold1" time="6.248" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="40.150" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E5_key4_ringgroup" time="45.487" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D3_fail_voicemail3_login" time="40.944" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="H2_leastRecent" time="37.043" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="CDR被叫方检测 【预期：1105 [6710(1105)] 实际：1100 [6701(1100)]】">
      <![CDATA[java.lang.AssertionError: CDR被叫方检测 【预期：1105 [6710(1105)] 实际：1100 [6701(1100)]】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:203)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:289)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.H2_leastRecent(Queue.java:1035)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- H2_leastRecent -->
  <testcase name="K1_rrmemory" time="22.018" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1000会第1个Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1000会第1个Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.K1_rrmemory(Queue.java:1112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- K1_rrmemory -->
  <testcase name="H1_leastRecent" time="17.588" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1103结束Ring，约响铃10s 【预期：4 实际：2】">
      <![CDATA[java.lang.AssertionError: 预期1103结束Ring，约响铃10s 【预期：4 实际：2】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.H1_leastRecent(Queue.java:1011)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- H1_leastRecent -->
  <testcase name="A4_AddQueues" time="31.744" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="N5_leave_join_empty" time="28.943" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="M1_ringall" time="85.577" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="CDR被叫方检测 【预期：1100 [6701(1100)] 实际：1000 [6714(1000)]】">
      <![CDATA[java.lang.AssertionError: CDR被叫方检测 【预期：1100 [6701(1100)] 实际：1000 [6714(1000)]】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:203)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:289)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.M1_ringall(Queue.java:1232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- M1_ringall -->
  <testcase name="N4_leave_join_empty" time="1.108" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="44.964" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="F3_dynamic_logoff6701" time="13.185" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D4_fail_ivr" time="49.571" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="19.960" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E2_key1_extension" time="44.070" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B5_Register" time="176.424" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.525" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="N1_leave_join_empty" time="35.560" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D7_fail_conference" time="52.075" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="N7_leave_join_empty" time="28.944" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="O1_delete" time="70.285" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D1_fail_hangup" time="11.085" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E8_key7_DialbyName" time="53.528" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="N3_leave_join_empty" time="28.991" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="39.166" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="D8_fail_DialbyName" time="54.893" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="A4_AddQueues" time="43.693" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.436" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="I2_fewestcalls" time="21.676" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1105会Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1105会Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.I2_fewestcalls(Queue.java:1075)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- I2_fewestcalls -->
  <testcase name="A4_AddQueues" time="41.916" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.573" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G4_AgentID" time="2.077" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="G9_warp_time20" time="26.051" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1101会Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1101会Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.G9_warp_time20(Queue.java:990)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- G9_warp_time20 -->
  <testcase name="I1_fewestcalls" time="21.639" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1102会Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1102会Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.I1_fewestcalls(Queue.java:1062)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- I1_fewestcalls -->
  <testcase name="A4_AddQueues" time="42.093" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="F1_dynamic_login6701" time="13.218" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="N2_leave_join_empty" time="1.096" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="F4_dynamic_call6701" time="52.398" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="H3_leastRecent" time="23.868" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue">
    <failure type="java.lang.AssertionError" message="预期1100会Ring 【预期：2 实际：4】">
      <![CDATA[java.lang.AssertionError: 预期1100会Ring 【预期：2 实际：4】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue.H3_leastRecent(Queue.java:1043)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- H3_leastRecent -->
  <testcase name="A1_initBeforeTest" time="0.026" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E1_key0_hangup" time="30.463" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="C5_fxo_6701" time="0.037" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="F7_dynamic_login6712" time="19.458" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.293" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="B2_AddInbound" time="20.564" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="N6_leave_join_empty" time="5.780" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="C7_e1_6701" time="0.010" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
  <testcase name="E7_key6_conference" time="50.493" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue"/>
</testsuite> <!-- com.yeastar.swebtest.testcase.DetailCase.pbxcase.Queue -->
