<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeastar-PC" name="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup" tests="26" failures="2" timestamp="16 Oct 2018 05:26:46 GMT" time="1363.832" errors="0">
  <testcase name="G_delete" time="88.258" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="E2_RingAll" time="64.184" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="C1_EditInRoute1" time="29.978" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="16.900" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="B1_EditRingGroupFxs" time="0.050" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="17.215" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="16.055" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F5_FailtoQueue" time="78.350" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup">
    <failure type="java.lang.AssertionError" message="CDR被叫方检测 【预期：1100 [6700(1100)] 实际：6700 [6700(1100)]】">
      <![CDATA[java.lang.AssertionError: CDR被叫方检测 【预期：1100 [6700(1100)] 实际：6700 [6700(1100)]】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:203)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:289)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:278)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup.F5_FailtoQueue(RingGroup.java:699)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- F5_FailtoQueue -->
  <testcase name="E1_Sequentially" time="48.665" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F9_loglout" time="8.267" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="C2_Backup" time="77.171" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F2_FailtoExtension" time="60.317" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F6_FailtoConference" time="72.087" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup">
    <failure type="java.lang.AssertionError" message="预计产生多条CDR，但没有找到匹配">
      <![CDATA[java.lang.AssertionError: 预计产生多条CDR，但没有找到匹配
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:346)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup.F6_FailtoConference(RingGroup.java:721)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- F6_FailtoConference -->
  <testcase name="F3_FailtoIVR" time="54.786" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="D_InboundtoRingGroup_a" time="338.577" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="15.981" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F7_FailtoVoicemail" time="62.009" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F8_check_Voicemail" time="43.070" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F4_FailtoRingGroup" time="67.989" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="18.805" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="F1_FailtoHangup" time="88.516" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="16.999" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="11.696" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A1_Init" time="31.429" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A2_AddRingGroups" time="19.060" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
  <testcase name="A3_add_cancel" time="17.418" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup"/>
</testsuite> <!-- com.yeastar.swebtest.testcase.DetailCase.pbxcase.RingGroup -->
