<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeastar-PC" name="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList" tests="17" failures="2" timestamp="20 Apr 2018 22:46:21 GMT" time="402.974" errors="0">
  <testcase name="E_checkPin" time="43.502" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList">
    <failure type="java.lang.AssertionError" message="外线呼出进入pinList 【预期：true 实际：false】">
      <![CDATA[java.lang.AssertionError: 外线呼出进入pinList 【预期：true 实际：false】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:333)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList.E_checkPin(PINList.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- E_checkPin -->
  <testcase name="K2_recovery_Pin" time="10.123" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="I_checkPin" time="37.489" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="H2_deleteOnePin_yes" time="27.836" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="K3_recovery_Disa" time="24.587" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="C_editDISA" time="29.261" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="J4_deleteAllPin_yes" time="13.352" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="A_addExtension" time="12.318" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="J2_deletePartPin_yes" time="13.425" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="F_deletePinNumber" time="22.863" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="K1_recovery_InRoute" time="28.909" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="J3_deleteAllPin_no" time="9.883" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="D_editInRoute" time="34.281" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="G_checkPin" time="42.480" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList">
    <failure type="java.lang.AssertionError" message="外线呼出进入pinList 【预期：true 实际：false】">
      <![CDATA[java.lang.AssertionError: 外线呼出进入pinList 【预期：true 实际：false】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:333)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList.G_checkPin(PINList.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- G_checkPin -->
  <testcase name="B_addPin" time="18.351" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="H1_deleteOnePin_no" time="19.887" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
  <testcase name="J1_deletePartPin_no" time="14.427" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList"/>
</testsuite> <!-- com.yeastar.swebtest.testcase.DetailCase.pbxcase.PINList -->
